create table USER_DATA (id bigint generated by default as identity, contact varchar(255),
 email varchar(255), enabled boolean not null, name varchar(255), password varchar(255), primary key (id));
INSERT INTO USER_DATA (contact, email, enabled, name, password)
VALUES ('831', 'chhavi.sri28@gmail.com', TRUE, 'Chhavi', '201301');;