create table USER_DATA (id bigint generated by default as identity,
contact varchar(255) unique,
 email varchar(255) unique,
 enabled boolean not null,
 name varchar(255),
 password varchar(255),
 last_login timestamp default CURRENT_TIMESTAMP,
 primary key (id));
INSERT INTO USER_DATA (contact, email, enabled, name, password,last_login)
VALUES ('831', 'chhavi.sri28@gmail.com', TRUE, 'Chhavi', '201301', CURRENT_TIMESTAMP);